### ISSUE TITLE
Ball Tracking Algorithm

### ISSUE THREAD

**Issue by rwmoskaluk** [chipjulien/DefensiveStats#3]
- [ ] Implement base ball tracking algorithm to BallTracker class
- [ ] Method for computing ball location on court
- [ ] Method for info regarding game info and ball stats to be stored and referenced later on
- [ ] Improve debugging hooks
