### ISSUE TITLE
Player Tracker Algorithm

### ISSUE THREAD

**Issue by rwmoskaluk** [chipjulien/DefensiveStats#4]
- [ ] Algorithm for identifying all players in a scene
- [ ] Method for differentiating player teams
- [ ] Method for recording player locations over time
- [ ] Method for identifying to court boundaries
- [ ] Method for differentiating court features (free throw line, 3 pt boundary, half court)
- [ ] Method for storing player stats and game stats to be stored
