### ISSUE TITLE
Improve tracking algorithms utilizing model based training

### ISSUE THREAD

**Issue by rwmoskaluk** [chipjulien/DefensiveStats#5]
- [ ] Explore various model based tracking algorithms
- [ ] Generate training and testing datasets
- [ ] Develop tagging based system for creating datasets
- [ ] Define metrics for model grading performance
